# -*- coding: utf-8 -*-
"""CPU Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J_FPS3Wa53taEjHI6_prVflQLaLz_3rU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def extract_filtered_rows(
    csv_path: str,
    out_path: str = None,
    encoding: str = "utf-8"
):
    # =========================
    # 1) Read CSV
    # =========================
    df = pd.read_csv(csv_path, encoding=encoding, low_memory=False)

    # =========================
    # 2) Column name compatibility
    # =========================
    def norm(s: str) -> str:
        s = str(s).strip().lower()
        s = s.replace("—", "-").replace("–", "-")  # Handle different dash types
        s = s.replace(" ", "_")
        s = s.replace("-", "_")
        return s

    col_map = {norm(c): c for c in df.columns}

    # Required standard column names -> possible aliases (after normalization)
    need = {
        "bright_level": ["bright_level", "brightness", "screen_brightness", "brightlevel"],
        "cpu_usage": ["cpu_usage", "cpuusage", "cpu_use", "cpu_util", "cpu_utilization", "cpu"],
        "gps_status": ["gps_status", "gps", "gpsstatus"],
        "screen_status": ["screen_status", "screen", "screenstatus"],
        "battery_charging_status": ["battery_charging_status", "charging_status", "batterychargingstatus"],
        "battery_connection_status": ["battery_connection_status", "connection_status", "batteryconnectionstatus"],
        "battery_power": ["battery_power", "power", "battery_power_w", "batterypower"],
    }

    # Find actual column names
    actual = {}
    missing = []
    for std_name, aliases in need.items():
        found = None
        for a in aliases:
            if a in col_map:
                found = col_map[a]
                break
        if found is None:
            missing.append(std_name)
        else:
            actual[std_name] = found

    if missing:
        raise KeyError(
            "Missing required columns in CSV (or column name mismatch):\n"
            + "\n".join(missing)
            + "\n\nCurrent CSV column names:\n"
            + ", ".join(df.columns[:50]) + (" ..." if len(df.columns) > 50 else "")
        )

    # =========================
    # 3) Convert to numeric (avoid string comparison issues)
    # =========================
    for k in actual:
        df[actual[k]] = pd.to_numeric(df[actual[k]], errors="coerce")

    # =========================
    # 4) Calculate brightness range corresponding to 20%~40% of 255
    # =========================
    bmin = int(np.ceil(0.20 * 255))  # 51
    bmax = int(np.floor(0.40 * 255))  # 102

    # =========================
    # 5) Filter conditions
    # =========================
    mask = (
        df[actual["bright_level"]].between(bmin, bmax, inclusive="both") &
        df[actual["cpu_usage"]].between(20, 60, inclusive="both") &
        (df[actual["gps_status"]] == 3) &
        (df[actual["screen_status"]] == 1) &
        (df[actual["battery_charging_status"]] == 3) &
        (df[actual["battery_connection_status"]] == 0)
    )

    df_f = df.loc[mask, [
        actual["bright_level"],
        actual["cpu_usage"],
        actual["gps_status"],
        actual["screen_status"],
        actual["battery_charging_status"],
        actual["battery_connection_status"],
        actual["battery_power"],
    ]].copy()

    # =========================
    # 6) Output statistics to verify filtering
    # =========================
    print("=== Filter Summary ===")
    print(f"Brightness range: {bmin} ~ {bmax} (i.e., 20%~40% of 255)")
    print(f"CPU Usage range: 20% ~ 60%")
    print(f"Rows kept: {len(df_f)} / {len(df)}")
    if len(df_f) > 0:
        print("\nCPU Usage statistics:")
        print(df_f[actual["cpu_usage"]].describe())
        print("\nBattery_power statistics:")
        print(df_f[actual["battery_power"]].describe())
    else:
        print("\n⚠️ No rows found: Please check column names, data units, or if conditions are too strict.")

    # =========================
    # 7) Save (optional)
    # =========================
    if out_path:
        df_f.to_csv(out_path, index=False, encoding="utf-8-sig")
        print(f"\nSaved to: {out_path}")

    return df_f

def plot_cpu_vs_battery_power(df_f):
    """
    x: cpu_usage
    y: battery_power
    Each row is one point
    """
    plt.figure(figsize=(7, 5))
    plt.scatter(
        df_f["cpu_usage"],
        df_f["battery_power"],
        s=20,
        alpha=0.6
    )

    plt.xlabel("CPU Usage (%)")
    plt.ylabel("Battery Power (W)")
    plt.title("Battery Power vs CPU Usage (each row = one point)")
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

def plot_cpu_vs_battery_with_mean_line(df_f):
    """
    Plot CPU usage vs battery power with overall mean lines
    """
    # 1) Calculate overall means
    mean_power = df_f["battery_power"].mean()
    mean_cpu = df_f["cpu_usage"].mean()

    # 2) Plot scatter points
    plt.figure(figsize=(7, 5))
    plt.scatter(
        df_f["cpu_usage"],
        df_f["battery_power"],
        s=20,
        alpha=0.6,
        label="data points"
    )

    # 3) Plot horizontal mean line
    plt.axhline(
        y=mean_power,
        linestyle="--",
        linewidth=2,
        color='red',
        label=f"mean battery_power = {mean_power:.3f}"
    )

    # 4) Plot vertical mean line
    plt.axvline(
        x=mean_cpu,
        linestyle="--",
        linewidth=2,
        color='green',
        label=f"mean CPU usage = {mean_cpu:.2f}%"
    )

    plt.xlabel("CPU Usage (%)")
    plt.ylabel("Battery Power (W)")
    plt.title("Battery Power vs CPU Usage\n(with overall mean lines)")
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    return mean_power

def cpu_usage_stats(df_f):
    """
    Calculate detailed statistics for CPU usage
    """
    mean_c = df_f["cpu_usage"].mean()
    median_c = df_f["cpu_usage"].median()
    std_c = df_f["cpu_usage"].std()
    min_c = df_f["cpu_usage"].min()
    max_c = df_f["cpu_usage"].max()

    print("\n=== CPU Usage Statistics ===")
    print(f"Mean CPU Usage   : {mean_c:.2f}%")
    print(f"Median CPU Usage : {median_c:.2f}%")
    print(f"Std CPU Usage    : {std_c:.2f}%")
    print(f"Min CPU Usage    : {min_c:.2f}%")
    print(f"Max CPU Usage    : {max_c:.2f}%")

    return {
        "mean": mean_c,
        "median": median_c,
        "std": std_c,
        "min": min_c,
        "max": max_c
    }

def battery_power_stats(df_f):
    """
    Calculate detailed statistics for battery power
    """
    mean_b = df_f["battery_power"].mean()
    median_b = df_f["battery_power"].median()
    std_b = df_f["battery_power"].std()
    min_b = df_f["battery_power"].min()
    max_b = df_f["battery_power"].max()

    print("\n=== Battery Power Statistics ===")
    print(f"Mean battery_power   : {mean_b:.3f}")
    print(f"Median battery_power : {median_b:.3f}")
    print(f"Std battery_power    : {std_b:.3f}")
    print(f"Min battery_power    : {min_b:.3f}")
    print(f"Max battery_power    : {max_b:.3f}")

    return {
        "mean": mean_b,
        "median": median_b,
        "std": std_b,
        "min": min_b,
        "max": max_b
    }

def correlation_analysis_cpu_battery(df_f):
    """
    Analyze correlation between CPU usage and battery power
    """
    print("\n=== Correlation Analysis ===")

    # Calculate correlation
    corr = df_f["cpu_usage"].corr(df_f["battery_power"])
    print(f"Correlation between CPU Usage and Battery Power: {corr:.3f}")

    # Interpret correlation strength
    if abs(corr) > 0.7:
        strength = "strong"
    elif abs(corr) > 0.3:
        strength = "moderate"
    else:
        strength = "weak"

    if corr > 0:
        direction = "positive"
    else:
        direction = "negative"

    print(f"This indicates a {strength} {direction} correlation.")

    if corr > 0:
        print("Interpretation: Higher CPU usage is associated with higher battery power consumption.")
    elif corr < 0:
        print("Interpretation: Higher CPU usage is associated with lower battery power.")
    else:
        print("Interpretation: No clear relationship between CPU usage and battery power.")

    return corr

def plot_cpu_vs_battery_with_regression(df_f):
    """
    Plot CPU usage vs battery power with regression line
    """
    plt.figure(figsize=(8, 6))

    # Scatter plot with brightness color coding
    scatter = plt.scatter(
        df_f["cpu_usage"],
        df_f["battery_power"],
        s=25,
        alpha=0.6,
        c=df_f["bright_level"],  # Use brightness as color encoding
        cmap='viridis',
        edgecolor='k',
        linewidth=0.3
    )

    plt.colorbar(scatter, label='Brightness Level')

    # Calculate and plot regression line
    try:
        z = np.polyfit(df_f["cpu_usage"], df_f["battery_power"], 1)
        p = np.poly1d(z)

        # Create sorted x-values for smooth regression line
        x_sorted = np.sort(df_f["cpu_usage"])
        plt.plot(x_sorted, p(x_sorted), "r--", linewidth=2,
                label=f'Regression: y = {z[0]:.3f}x + {z[1]:.3f}')

        # Calculate R² value
        y_pred = p(df_f["cpu_usage"])
        y_mean = df_f["battery_power"].mean()
        ss_res = np.sum((df_f["battery_power"] - y_pred) ** 2)
        ss_tot = np.sum((df_f["battery_power"] - y_mean) ** 2)
        r_squared = 1 - (ss_res / ss_tot)

        # Display R² value on plot
        plt.text(0.05, 0.95, f'R² = {r_squared:.3f}',
                transform=plt.gca().transAxes,
                fontsize=12,
                verticalalignment='top',
                bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    except Exception as e:
        print(f"Could not calculate regression line: {e}")

    plt.xlabel("CPU Usage (%)", fontsize=12)
    plt.ylabel("Battery Power (W)", fontsize=12)
    plt.title("Battery Power vs CPU Usage\n(with regression line)", fontsize=14, fontweight='bold')
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()


# Main execution
if __name__ == "__main__":
    print("="*60)
    print("CPU USAGE vs BATTERY POWER ANALYSIS")
    print("="*60)

    # Read and filter data from raw file
    df_filtered = extract_filtered_rows(
        csv_path=r"/content/ab47b5f5ecded6b8_20221207_dynamic_processed.csv",
        out_path=r"/content/filtered_cpu_battery_data.csv"
    )

    # Basic scatter plot
    plot_cpu_vs_battery_power(df_filtered)

    # Scatter plot with mean lines
    mean_power = plot_cpu_vs_battery_with_mean_line(df_filtered)
    print(f"\nOverall Mean Battery Power: {mean_power:.3f}")

    # CPU usage statistics
    cpu_stats = cpu_usage_stats(df_filtered)

    # Battery power statistics
    battery_stats = battery_power_stats(df_filtered)

    # Correlation analysis
    correlation = correlation_analysis_cpu_battery(df_filtered)

    # Scatter plot with regression line
    plot_cpu_vs_battery_with_regression(df_filtered)

    # Data preview
    print("\n" + "="*60)
    print("DATA PREVIEW")
    print("="*60)
    print(f"Total filtered rows: {len(df_filtered)}")
    print("\nFirst 10 rows:")
    print(df_filtered[['cpu_usage', 'battery_power', 'bright_level']].head(10))

    print("\n" + "="*60)
    print("ANALYSIS COMPLETE")
    print("="*60)