# -*- coding: utf-8 -*-
"""Data usage Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeXivVpVu8JADZay40WLDBjeizxWNxPn

data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df = pd.read_csv(
    "/content/MobileDeviceUsageexport2026-02-0102-59-00.csv",
    low_memory=False
)
print(df.columns)

V = 3.7

df["P_data"] = df["Battery Drain (mAh/day)"] * V / (1000 * 24)

X = df[["Data Usage (MB/day)"]]   # MB/day
y = df["P_data"]           # W

model = LinearRegression()
model.fit(X, y)

k = model.coef_[0]
b = model.intercept_

print(f"P_data(x) = {k:.6f} * x + {b:.6f}")

x_line = np.linspace(X.min(), X.max(), 200).reshape(-1,1)
y_pred = model.predict(x_line)

plt.scatter(X, y, alpha=0.5)
plt.plot(x_line, y_pred)
plt.xlabel("Data usage (MB/day)")
plt.ylabel("Equivalent data power (W)")
plt.title("Data Usage vs Battery Power")
plt.grid(True)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
# import tkinter as tk
# from tkinter import simpledialog # Removed tkinter for headless environment

# =========================
# 1) Load your data file
# =========================
file_path = "MobileDeviceUsageexport2026-02-0102-59-00.csv"
df = pd.read_csv(file_path)
print("✅ File loaded successfully")

# =========================
# 2) Specify X and Y columns
# =========================
x_col = "Data Usage (MB/day)"
y_col = "Battery Drain (mAh/day)"

x = df[x_col].to_numpy(dtype=float)
y = df[y_col].to_numpy(dtype=float)

print(f"\n📊 Data Statistics:")
print(f"Number of samples: {len(x)}")
print(f"X range: {x.min():.1f} ~ {x.max():.1f}")
print(f"Y range: {y.min():.1f} ~ {y.max():.1f}")

# =========================
# 3) Basic statistics
# =========================
coef = np.polyfit(x, y, 1)
r_p, p_p = pearsonr(x, y)
print(f"\n📌 Pearson correlation: {r_p:.4f}")
print(f"📌 Linear fit: y = {coef[0]:.4f}x + {coef[1]:.2f}")

# =========================
# 4) Select interval using input() prompts
# =========================
print("\n" + "="*60)
print("📌 SELECT YOUR INTERVAL")
print("="*60)

# Replace simpledialog with input()
while True:
    try:
        left_bound_str = input(f"Enter LEFT boundary (min {x.min():.1f}, max {x.max():.1f}): ").strip()
        left_bound = float(left_bound_str)
        if not (x.min() <= left_bound <= x.max()):
            print("❌ Input out of valid range.")
            continue
        break
    except ValueError:
        print("❌ Invalid input. Please enter a number.")

while True:
    try:
        right_bound_str = input(f"Enter RIGHT boundary (min {left_bound + 1:.1f}, max {x.max():.1f}): ").strip()
        right_bound = float(right_bound_str)
        if not (left_bound + 1 <= right_bound <= x.max()):
            print("❌ Input out of valid range.")
            continue
        break
    except ValueError:
        print("❌ Invalid input. Please enter a number.")

selected_range = (left_bound, right_bound)
print(f"✅ Your selected interval: {selected_range[0]:.1f} ~ {selected_range[1]:.1f} MB/day")

# Filter data in the interval
mask = (x >= selected_range[0]) & (x <= selected_range[1])
x_selected = x[mask]
y_selected = y[mask]

print(f"📊 Points in interval: {len(x_selected)}")

if len(x_selected) > 0:
    x_median = float(np.median(x_selected))
    y_median = float(np.median(y_selected))
    print(f"🎯 Median point: ({x_median:.1f}, {y_median:.1f})")
else:
    print("⚠️ No data points in this interval!")
    x_median = None
    y_median = None

# =========================
# 5) Your formula
# =========================
def your_formula(x):
    """Your formula: P(x) = 5430.985 - 5453.666 * exp(-0.0004037 * x)"""
    return 5430.985 - 5453.666 * np.exp(-0.0004037 * x)

# =========================
# 6) Create single plot: Your formula curve
# =========================
plt.figure(figsize=(12, 8))

# Plot all data points
plt.scatter(x, y, alpha=0.15, s=30, color='gray', label="All data points")

# Plot your formula curve
x_curve = np.linspace(0, 2500, 500)
y_curve = your_formula(x_curve)
plt.plot(x_curve, y_curve, 'red', linewidth=4,
         label='Your formula: $5430.985 - 5453.666e^{-0.0004037x}$')

# Plot selected interval data points
if len(x_selected) > 0:
    plt.scatter(x_selected, y_selected, alpha=0.8, s=60, color='red',
                label=f'Selected data ({selected_range[0]:.0f}-{selected_range[1]:.0f} MB/day)')

# Plot median point
if x_median is not None:
    plt.scatter(x_median, y_median, s=200, color='yellow', edgecolors='black',
                linewidth=3, label=f'Median: ({x_median:.1f}, {y_median:.1f})')

# Add saturation line
saturation_value = 5430.985
plt.axhline(y=saturation_value, color='orange', linestyle='--', alpha=0.6,
            label=f'Saturation limit: {saturation_value:.0f} mAh/day')

# Highlight selected interval area
plt.axvspan(selected_range[0], selected_range[1], alpha=0.1, color='red',
            label=f'Selected interval')

# Plot settings
plt.xlabel(x_col, fontsize=12)
plt.ylabel(y_col, fontsize=12)
plt.title('Your Formula Curve with Selected Data Points', fontsize=14)
plt.grid(True, alpha=0.3)
plt.legend(loc='best', fontsize=10)

# Set appropriate limits
plt.xlim(0, 2500)
plt.ylim(0, 3500)

plt.tight_layout()
plt.show()

# =========================
# 7) Print summary
# =========================
print("\n" + "="*60)
print("📊 ANALYSIS SUMMARY")
print("="*60)
print(f"Your interval: {selected_range[0]:.1f} ~ {selected_range[1]:.1f} MB/day")
print(f"Points in interval: {len(x_selected)}")
if x_median is not None:
    print(f"Median point: X = {x_median:.1f}, Y = {y_median:.1f}")
print(f"\nYour formula: P(x) = 5430.985 - 5453.666 * exp(-0.0004037 * x)")
print(f"Saturation value: {saturation_value:.3f} mAh/day")
print(f"Initial value (x=0): {your_formula(0):.3f} mAh/day")