# -*- coding: utf-8 -*-
"""DatasetCleaning_PscreenRegression_PcpuRegression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12I_LpWRbwd6TsizjAiLLp5S8LAlAZY9m
"""

import pandas as pd

mcm_data_1 = pd.read_csv('/content/ab47b5f5ecded6b8_20220512_dynamic_processed.csv')
mcm_data_2 = pd.read_csv('/content/ab47b5f5ecded6b8_20220712_dynamic_processed.csv')
mcm_data_3 = pd.read_csv('/content/ab47b5f5ecded6b8_20221207_dynamic_processed.csv')
mcm_data_4 = pd.read_csv('/content/ab47b5f5ecded6b8_20221208_dynamic_processed.csv')
mcm_data_5 = pd.read_csv('/content/ab47b5f5ecded6b8_20221209_dynamic_processed.csv')
mcm_data_6 = pd.read_csv('/content/ab47b5f5ecded6b8_20221210_dynamic_processed.csv')
mcm_data_7 = pd.read_csv('/content/ab47b5f5ecded6b8_20221206_dynamic_processed.csv')
mcm_data_8 = pd.read_csv('/content/ab47b5f5ecded6b8_20220812_dynamic_processed.csv')
mcm_data_9 = pd.read_csv('/content/ab47b5f5ecded6b8_20220912_dynamic_processed.csv')
mcm_data_10 = pd.read_csv('/content/ab47b5f5ecded6b8_20221205_dynamic_processed.csv')

mcm_data_list = [mcm_data_1, mcm_data_2, mcm_data_3, mcm_data_4, mcm_data_5, mcm_data_6, mcm_data_7, mcm_data_8, mcm_data_9, mcm_data_10]

mcm_data_1.columns

delete = ['device_id', 'timestamp', 'screen_on_time', 'bright_mode', 'saving_mode', 'bluetooth', 'nfc', 'flashlight', 'airplane_mode', 'fingerprint', 'orientation', 'battery_health', 'mobile_roaming', 'mobile_rx', 'mobile_tx', 'wifi_ap',
          'wifi_rx', 'wifi_tx', 'network_operator', 'sim_operator', 'mcc', 'mnc', 'ring_mode', 'sound_level', 'playback_status', 'rom_usage', 'rom_free', 'cpu_temperature', 'up_time',
          'sleep_time', 'frequency_core0', 'frequency_core1', 'frequency_core2',
          'frequency_core3', 'frequency_core4', 'frequency_core5',
          'frequency_core6', 'frequency_core7', 'foreground_app', 'collected']

for data in mcm_data_list:
  data = data.drop(columns=delete, inplace=True)

mcm_data_1.columns

"""screen_status = 1

battery_charging_status = 3

battery_connection_status = 0

-------------------------
when not chosen

bright_level = 5

network_mode = 1

mobile_mode = 0

mobile_status = 0

wifi_status = 1

wifi_intensity = (use the most one after filtering other, and use +- 1)

wifi_speed = 192

cpu_usage = 19
"""

for i in range(1, len(mcm_data_list) + 1):
  data = mcm_data_list[i-1]
  globals()[f"mcm_data_filtered_{i}"] = data.loc[(data['screen_status'] == 1) &
                                        (data['battery_charging_status'] == 3)]
  print(globals()[f"mcm_data_filtered_{i}"].shape)

mcm_data_filtered_list = [mcm_data_filtered_1, mcm_data_filtered_2, mcm_data_filtered_3,
                          mcm_data_filtered_4, mcm_data_filtered_5, mcm_data_filtered_6, mcm_data_filtered_7, mcm_data_filtered_8, mcm_data_filtered_9, mcm_data_filtered_10]

columns_to_filter = [
    'bright_level',
    'gps_status',
    'gps_activity',
    'network_mode',
    'mobile_status',
    'wifi_status',
    'wifi_intensity',
    'wifi_speed',
    'cpu_usage'
]

for i in range(1, len(mcm_data_filtered_list) + 1):
    print(f'No.{i} dataset processing...')
    data = mcm_data_filtered_list[i-1]

    for skipped_column in columns_to_filter:
        mcm_data_iterative = data.copy()

        for col in columns_to_filter:
            if col == skipped_column:
                continue

            if mcm_data_iterative.empty:
                break

            if col == 'wifi_intensity':
                counts = mcm_data_iterative['wifi_intensity'].value_counts()
                if not counts.empty and len(counts) >= 3:
                    min_val = int(counts.index.min())
                    max_val = int(counts.index.max())

                    best_sum = -1
                    best_range = []

                    for start_val in range(min_val, max_val - 1):
                        current_range = [start_val, start_val + 1, start_val + 2]
                        current_sum = sum(counts.get(val, 0) for val in current_range)

                        if current_sum > best_sum:
                            best_sum = current_sum
                            best_range = current_range

                    mcm_data_iterative = mcm_data_iterative[mcm_data_iterative[col].isin(best_range)]
            else:
                mcm_data_iterative = mcm_data_iterative[mcm_data_iterative[col] == mcm_data_iterative[col].mode()[0]]


        globals()[f"mcm_data_{i}_{skipped_column}"] = mcm_data_iterative

        print(f"Excluded Column: {skipped_column:15} | Final row count: {len(mcm_data_iterative)}")

import matplotlib.pyplot as plt
import numpy as np

# Define the columns to analyze
columns_to_plot = [
    'bright_level',
    'gps_status',
    'gps_activity',
    'network_mode',
    'mobile_status',
    'wifi_status',
    'wifi_intensity',
    'wifi_speed',
    'cpu_usage'
]

# Create subplots for each feature
n_cols = 3
n_rows = int(np.ceil(len(columns_to_plot) / n_cols))

fig, axes = plt.subplots(n_rows, n_cols, figsize=(18, 6 * n_rows))
axes = axes.flatten() if n_rows > 1 else [axes]

for idx, col in enumerate(columns_to_plot):
    ax = axes[idx]

    # Process each dataset
    for i in range(1, len(mcm_data_filtered_list) + 1):
        data = mcm_data_filtered_list[i-1]

        if col in data.columns and 'battery_power' in data.columns:
            # Group by the current column and calculate average battery power
            grouped_data = (
                data
                .groupby(col)['battery_power']
                .mean()
                .reset_index()
                .sort_values(by=col)
            )

            ax.plot(
                grouped_data[col],
                grouped_data['battery_power'],
                label=f'Dataset {i}',
                marker='o',
                linewidth=2,
                markersize=6
            )

    ax.set_title(f'Battery Power vs {col}')
    ax.set_xlabel(col)
    ax.set_ylabel('Average Battery Power')

    # 🔴 关键改动：反转 y 轴
    ax.invert_yaxis()

    ax.legend()
    ax.grid(True, linestyle='--', alpha=0.7)

# Hide unused subplots
for j in range(idx + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

# Print summary statistics for each column
print("Summary Statistics:")
for col in columns_to_plot:
    print(f"\n{col}:")
    for i in range(1, len(mcm_data_filtered_list) + 1):
        data = mcm_data_filtered_list[i-1]
        if col in data.columns and 'battery_power' in data.columns:
            grouped_data = data.groupby(col)['battery_power'].mean()
            print(f"  Dataset {i}: {len(grouped_data)} unique {col} values")

"""# Pscreen(t)

"""

import numpy as np
import matplotlib.pyplot as plt

# 如果你装了 scipy（一般都有），用它做非线性拟合更稳
try:
    from scipy.optimize import curve_fit
    SCIPY_OK = True
except Exception:
    SCIPY_OK = False

# =========================
# 1) Log model: p = A + C * log(b + b0)
# =========================
def f_log(b, A, C, b0):
    b = np.asarray(b, float)
    return A + C * np.log(b + b0)

def fit_log_model(b, p, w=None, b0_min=1e-6):
    """
    拟合 log: p = A + C log(b+b0)
    返回 dict: params, rmse, r2, aic, yhat
    """
    b = np.asarray(b, float)
    p = np.asarray(p, float)
    if b.shape != p.shape:
        raise ValueError("b and p must have the same shape.")

    # 权重（可选）：w 越大越重要
    if w is None:
        w = np.ones_like(p, float)
    else:
        w = np.asarray(w, float)
        if w.shape != p.shape:
            raise ValueError("w must have same shape as p.")
        if np.any(w < 0) or np.sum(w) <= 0:
            raise ValueError("weights must be non-negative and sum > 0.")

    # 过滤无效点：b+b0 必须 > 0
    # b0 是要拟合的，所以这里只先过滤 b 非常极端的情况
    mask = np.isfinite(b) & np.isfinite(p)
    b = b[mask]; p = p[mask]; w = w[mask]

    if len(b) < 6:
        raise ValueError("Too few points for fitting (need >= 6).")

    # 初值：A 取加权均值；C 取一个小量；b0 取让 b+b0>0 的正数
    A0 = np.sum(w * p) / np.sum(w)
    C0 = 0.1
    b0_0 = max(b0_min, 0.1 * (np.max(b) - np.min(b) + 1e-9))
    p0 = [A0, C0, b0_0]

    # 参数约束：b0 > 0 防止 log 定义域问题
    lower = [-np.inf, -np.inf, b0_min]
    upper = [ np.inf,  np.inf, np.inf]

    if SCIPY_OK:
        # curve_fit 不支持直接权重，但支持 sigma；最小化 sum(((y-f)/sigma)^2)
        # 设 sigma = 1/sqrt(w) => 等价于加权最小二乘
        sigma = 1.0 / np.sqrt(np.maximum(w, 1e-12))

        popt, pcov = curve_fit(
            f_log, b, p,
            p0=p0, bounds=(lower, upper),
            sigma=sigma, absolute_sigma=False,
            maxfev=200000
        )
        A, C, b0 = popt
    else:
        # 没有 scipy 的 fallback：固定 b0 网格搜索 + 线性回归 A,C
        # （能跑但更粗糙）
        b0_candidates = np.linspace(b0_0 * 0.1, b0_0 * 10, 80)
        best = None
        for b0 in b0_candidates:
            x = np.log(b + b0)
            X = np.column_stack([np.ones_like(x), x])
            Xw = X * w[:, None]
            beta = np.linalg.lstsq(X.T @ Xw, X.T @ (w * p), rcond=None)[0]
            A, C = beta
            yhat = A + C * x
            sse = np.sum(w * (p - yhat) ** 2)
            if best is None or sse < best["sse"]:
                best = {"A": A, "C": C, "b0": b0, "sse": sse}
        A, C, b0 = best["A"], best["C"], best["b0"]

    # 预测与指标（加权）
    yhat = f_log(b, A, C, b0)
    resid = p - yhat
    sse = np.sum(w * resid**2)

    # 加权 RMSE
    rmse = np.sqrt(sse / np.sum(w))

    # 加权 R2
    pbar = np.sum(w * p) / np.sum(w)
    sst = np.sum(w * (p - pbar) ** 2)
    r2 = 1.0 - (sse / sst if sst > 0 else np.nan)

    # AIC（用 n 近似）
    n = len(p)
    k_params = 3  # A, C, b0
    aic = n * np.log((sse / n) + 1e-12) + 2 * k_params

    return {
        "A": float(A), "C": float(C), "b0": float(b0),
        "rmse": float(rmse), "r2": float(r2), "aic": float(aic),
        "b_used": b, "p_used": p, "w_used": w, "yhat_used": yhat
    }

# =========================
# 2) Plot: invert y-axis so -3 is above -1
# =========================
def plot_data_and_logfit(b, p, fit_res, title="Log fit with inverted y-axis"):
    b = np.asarray(b, float)
    p = np.asarray(p, float)

    bb = np.linspace(np.min(b), np.max(b), 400)
    yy = f_log(bb, fit_res["A"], fit_res["C"], fit_res["b0"])

    plt.figure(figsize=(10, 6))
    plt.scatter(b, p, s=30, label="data")
    plt.plot(bb, yy, lw=2, label=f"log: A + C log(b+b0)\nAIC={fit_res['aic']:.2f}, RMSE={fit_res['rmse']:.4f}")
    plt.xlabel("Brightness b")
    plt.ylabel("Power metric p (more negative = higher power)")
    plt.title(title)
    plt.grid(True, linestyle="--", alpha=0.5)
    plt.legend()

    # 关键：反转 y 轴，让 -3 在 -1 上面
    plt.gca().invert_yaxis()

    plt.show()

# =========================
# 3) RUN (你只要保证 b, p 已经存在)
# =========================
# 可选：如果你有每个 bin 的样本数 cnt，就用它做权重更稳健
# w = cnt
w = None

fit_res = fit_log_model(b, p, w=w)

print("Log model: p = A + C log(b+b0)")
print(f"params: A={fit_res['A']:.6f}, C={fit_res['C']:.6f}, b0={fit_res['b0']:.6f}")
print(f"RMSE={fit_res['rmse']:.4f}, R2={fit_res['r2']:.4f}, AIC={fit_res['aic']:.2f}")

plot_data_and_logfit(b, p, fit_res, title="Log fit (y-axis inverted for physical intuition)")

import numpy as np
from scipy.optimize import curve_fit

def f_log(b, A, C, b0):
    return A + C*np.log(b + b0)

def fit_log_model(b, p, w=None, b0_min=1e-6):
    b = np.asarray(b, float); p = np.asarray(p, float)
    if w is None:
        w = np.ones_like(p)
    else:
        w = np.asarray(w, float)

    A0 = np.sum(w*p)/np.sum(w)
    C0 = 0.1
    b0_0 = max(b0_min, 0.1*(np.max(b)-np.min(b)+1e-9))
    p0 = [A0, C0, b0_0]
    lower = [-np.inf, -np.inf, b0_min]
    upper = [ np.inf,  np.inf, np.inf]

    sigma = 1.0/np.sqrt(np.maximum(w, 1e-12))
    popt, _ = curve_fit(
        f_log, b, p, p0=p0, bounds=(lower, upper),
        sigma=sigma, absolute_sigma=False, maxfev=200000
    )
    A, C, b0 = popt
    return A, C, b0

def eval_metrics(y, yhat, w=None):
    y = np.asarray(y); yhat = np.asarray(yhat)
    err = y - yhat
    if w is None:
        rmse = np.sqrt(np.mean(err**2))
        mae = np.mean(np.abs(err))
    else:
        w = np.asarray(w, float)
        rmse = np.sqrt(np.sum(w*err**2)/np.sum(w))
        mae = np.sum(w*np.abs(err))/np.sum(w)
    medae = np.median(np.abs(err))
    return rmse, mae, medae

def kfold_log(b, p, K=5, seed=0, w=None):
    b = np.asarray(b, float); p = np.asarray(p, float)
    if w is not None:
        w = np.asarray(w, float)

    rng = np.random.default_rng(seed)
    idx = np.arange(len(b))
    rng.shuffle(idx)
    folds = np.array_split(idx, K)

    rows = []
    for k in range(K):
        te = folds[k]
        tr = np.setdiff1d(idx, te)

        w_tr = None if w is None else w[tr]
        w_te = None if w is None else w[te]

        A, C, b0 = fit_log_model(b[tr], p[tr], w=w_tr)
        yhat_tr = f_log(b[tr], A, C, b0)
        yhat_te = f_log(b[te], A, C, b0)

        rmse_tr, mae_tr, medae_tr = eval_metrics(p[tr], yhat_tr, w=w_tr)
        rmse_te, mae_te, medae_te = eval_metrics(p[te], yhat_te, w=w_te)

        rows.append({
            "fold": k, "A": A, "C": C, "b0": b0,
            "train_rmse": rmse_tr, "test_rmse": rmse_te,
            "train_mae": mae_tr, "test_mae": mae_te,
            "train_medae": medae_tr, "test_medae": medae_te,
        })
    return rows

# ---- run ----
w = None  # or cnt
rows = kfold_log(b, p, K=5, seed=0, w=w)
test_rmses = [r["test_rmse"] for r in rows]
print("K-fold CV (log)")
print("test_rmse per fold:", [round(x, 4) for x in test_rmses])
print("mean test_rmse:", float(np.mean(test_rmses)))
print("std  test_rmse:", float(np.std(test_rmses)))
print("b0 per fold:", [round(r["b0"], 3) for r in rows])

"""# Pcpu(t)"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# 取 u >= 40
u0 = 40.0
mask = g_cpu["u"].values >= u0

u = g_cpu.loc[mask, "u"].values.astype(float)
p = g_cpu.loc[mask, "mean_smooth"].values.astype(float)
w = g_cpu.loc[mask, "count"].values.astype(float)

print("points used:", len(u))
def f_linear(u, a, b):
    return a * u + b
sigma = 1.0 / np.sqrt(np.maximum(w, 1e-12))

popt, _ = curve_fit(
    f_linear,
    u, p,
    sigma=sigma,
    absolute_sigma=False,
    maxfev=200000
)

a_hat, b_hat = popt
print(f"Linear fit: p = {a_hat:.4f} * u + {b_hat:.4f}")
def eval_metrics(y, yhat, w=None):
    y = np.asarray(y); yhat = np.asarray(yhat)
    err = y - yhat
    if w is None:
        rmse = np.sqrt(np.mean(err**2))
        mae = np.mean(np.abs(err))
    else:
        w = np.asarray(w, float)
        rmse = np.sqrt(np.sum(w*err**2)/np.sum(w))
        mae = np.sum(w*np.abs(err))/np.sum(w)
    medae = np.median(np.abs(err))
    return rmse, mae, medae


def kfold_linear(u, p, w=None, K=5, seed=0):
    u = np.asarray(u, float); p = np.asarray(p, float)
    if w is not None:
        w = np.asarray(w, float)

    rng = np.random.default_rng(seed)
    idx = np.arange(len(u))
    rng.shuffle(idx)
    folds = np.array_split(idx, K)

    rows = []
    for kfold in range(K):
        te = folds[kfold]
        tr = np.setdiff1d(idx, te)

        w_tr = None if w is None else w[tr]
        w_te = None if w is None else w[te]

        sigma_tr = None if w_tr is None else 1.0 / np.sqrt(np.maximum(w_tr, 1e-12))

        popt, _ = curve_fit(
            f_linear,
            u[tr], p[tr],
            sigma=sigma_tr,
            absolute_sigma=False,
            maxfev=200000
        )
        a, b = popt

        yhat_tr = f_linear(u[tr], a, b)
        yhat_te = f_linear(u[te], a, b)

        rmse_tr, mae_tr, medae_tr = eval_metrics(p[tr], yhat_tr, w=w_tr)
        rmse_te, mae_te, medae_te = eval_metrics(p[te], yhat_te, w=w_te)

        rows.append({
            "fold": kfold,
            "a": a, "b": b,
            "train_rmse": rmse_tr, "test_rmse": rmse_te,
            "train_mae": mae_tr, "test_mae": mae_te,
            "train_medae": medae_tr, "test_medae": medae_te,
        })
    return rows


rows_lin = kfold_linear(u, p, w=w, K=5, seed=0)

test_rmses = [r["test_rmse"] for r in rows_lin]
print("\nK-fold CV (linear, u>=40)")
print("test_rmse per fold:", [round(float(x), 4) for x in test_rmses])
print("mean test_rmse:", float(np.mean(test_rmses)))
print("std  test_rmse:", float(np.std(test_rmses)))
print("slope per fold:", [round(r["a"], 4) for r in rows_lin])
uu = np.linspace(u.min(), u.max(), 400)
pp = f_linear(uu, a_hat, b_hat)

plt.figure(figsize=(10,6))
plt.scatter(u, p, s=40, label="data (u>=40)")
plt.plot(uu, pp, lw=3, label=f"linear fit: p={a_hat:.3f}u+{b_hat:.3f}")

plt.xlabel("CPU usage (%) (binned)")
plt.ylabel("Battery Power (W)")
plt.title("CPU power model (linear, u>=40)")
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend()
plt.gca().invert_yaxis()
plt.show()

mask = g_cpu["u"] >= 30
plt.figure(figsize=(10,6))
plt.scatter(g_cpu.loc[~mask, "u"], g_cpu.loc[~mask, "mean_smooth"], label="<30% (discard)", alpha=0.6)
plt.scatter(g_cpu.loc[mask, "u"],  g_cpu.loc[mask, "mean_smooth"],  label=">=30% (fit)", alpha=0.9)
plt.xlabel("CPU usage (%)")
plt.ylabel("Battery Power (W)")
plt.title("CPU usage split at 30%")
plt.grid(True, linestyle="--", alpha=0.5)
plt.legend()
plt.gca().invert_yaxis()
plt.show()



"""# Pgps

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# =========================================================
# 0) 可配置参数
# =========================================================
P_COL = "battery_power"
GPS_STATUS_COL = "gps_status"
GPS_ACTIVITY_COL = "gps_activity"

# 你之前用的控制列（除了目标列之外，我们都固定）
CONTROL_COLS_BASE = [
    "bright_level",
    "network_mode",
    "mobile_status",
    "wifi_status",
    "wifi_intensity",
    "wifi_speed",
    "cpu_usage",
    # GPS 相关会在函数里按需剔除/控制
]

MIN_COUNT_PER_STATE = 20     # 每个状态(0/1)至少要多少点才纳入统计
USE_MODE_CONTROL = True      # True: 其他变量固定在众数；False: 不控制其它变量（只做粗统计）


# =========================================================
# 1) 控制变量过滤：把除 target_col 外的控制列固定住
# =========================================================
def _filter_by_controls(df, control_cols, min_count=1):
    """
    将 control_cols 中每个变量固定为“众数”或“最密集区间”
    注意：wifi_intensity 用你之前的 3 连续值窗口策略
    """
    out = df.copy()

    for col in control_cols:
        if out.empty:
            break
        if col not in out.columns:
            continue

        if col == "wifi_intensity":
            counts = out[col].value_counts(dropna=True)
            if counts.empty or len(counts) < 3:
                # 样本太少，不做进一步过滤
                continue

            # 找到样本数最多的连续 3 档区间
            min_val = int(counts.index.min())
            max_val = int(counts.index.max())
            best_sum = -1
            best_range = None
            for start_val in range(min_val, max_val - 1):
                r = [start_val, start_val + 1, start_val + 2]
                s = sum(counts.get(v, 0) for v in r)
                if s > best_sum:
                    best_sum = s
                    best_range = r

            if best_range is not None:
                out = out[out[col].isin(best_range)]
        else:
            # 众数固定
            mode_vals = out[col].mode(dropna=True)
            if len(mode_vals) == 0:
                continue
            out = out[out[col] == mode_vals.iloc[0]]

    return out


# =========================================================
# 2) 计算“开关增量”：E[P|G=1] - E[P|G=0]
# =========================================================
def estimate_switch_delta(
    data_list,
    switch_col,
    p_col=P_COL,
    control_cols=None,
    min_count_per_state=MIN_COUNT_PER_STATE,
    use_control=True,
):
    """
    返回：
      - per_dataset: 每个数据集的 mean0, mean1, count0, count1, delta
      - pooled: 合并加权（按 count0+count1 权重）后的总体估计
    """
    rows = []

    for i, df in enumerate(data_list, start=1):
        if switch_col not in df.columns or p_col not in df.columns:
            continue

        x = df[[switch_col, p_col] + ([c for c in (control_cols or []) if c in df.columns])].dropna()

        if use_control and control_cols:
            # 控制变量法：固定除 switch_col 之外的控制列
            ctrl = [c for c in control_cols if c != switch_col]
            x = _filter_by_controls(x, ctrl)

        if x.empty:
            rows.append({"dataset": i, "ok": False, "reason": "empty after control"})
            continue

        g0 = x[x[switch_col] == 0][p_col]
        g1 = x[x[switch_col] == 1][p_col]

        c0, c1 = int(g0.shape[0]), int(g1.shape[0])
        if c0 < min_count_per_state or c1 < min_count_per_state:
            rows.append({
                "dataset": i, "ok": False,
                "reason": f"insufficient counts (0:{c0}, 1:{c1})"
            })
            continue

        m0, m1 = float(g0.mean()), float(g1.mean())
        delta = m1 - m0

        rows.append({
            "dataset": i,
            "ok": True,
            "mean0": m0, "mean1": m1,
            "count0": c0, "count1": c1,
            "delta_raw": delta,
            # 直觉版：正数表示“功耗增加”
            "delta_consumption": -delta
        })

    per_dataset = pd.DataFrame(rows)

    # pooled：对每个数据集的 delta 做样本数加权
    ok = per_dataset[per_dataset["ok"] == True].copy()
    if ok.empty:
        pooled = None
    else:
        w = (ok["count0"] + ok["count1"]).astype(float)
        pooled = {
            "switch_col": switch_col,
            "n_datasets_used": int(ok.shape[0]),
            "pooled_delta_raw": float(np.sum(w * ok["delta_raw"]) / np.sum(w)),
            "pooled_delta_consumption": float(np.sum(w * ok["delta_consumption"]) / np.sum(w)),
        }

    return per_dataset, pooled


# =========================================================
# 3) 画图：0/1 均值条形图 + ΔP 图
# =========================================================
def plot_switch_summary(per_dataset, pooled, title_prefix=""):
    ok = per_dataset[per_dataset["ok"] == True].copy()
    if ok.empty:
        print("No valid datasets for plotting.")
        return

    # ---- 图1：每个数据集的 mean0/mean1 ----
    fig, ax = plt.subplots(figsize=(12, 6))

    x = np.arange(ok.shape[0])
    width = 0.35

    ax.bar(x - width/2, ok["mean0"].values, width, label="state=0 mean(P)")
    ax.bar(x + width/2, ok["mean1"].values, width, label="state=1 mean(P)")

    ax.set_xticks(x)
    ax.set_xticklabels([f"D{int(d)}" for d in ok["dataset"].values])
    ax.set_xlabel("Dataset")
    ax.set_ylabel("Mean battery_power (raw)")
    ax.set_title(f"{title_prefix} mean(P) at state=0 vs 1 (per dataset)")
    ax.grid(True, linestyle="--", alpha=0.4)
    ax.legend()

    # 你喜欢把 y 轴翻过来（更负=更耗电）
    ax.invert_yaxis()
    plt.tight_layout()
    plt.show()

    # ---- 图2：每个数据集的 ΔP（直觉版：正数=功耗增加）----
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.bar(x, ok["delta_consumption"].values)
    ax.set_xticks(x)
    ax.set_xticklabels([f"D{int(d)}" for d in ok["dataset"].values])

    ax.set_xlabel("Dataset")
    ax.set_ylabel("ΔP (consumption) = -(mean1-mean0)  (positive => more power)")
    ax.set_title(f"{title_prefix} estimated GPS power increment per dataset")
    ax.grid(True, linestyle="--", alpha=0.4)

    # 这里不要 invert（因为我们已经转成“正数表示增加”）
    plt.tight_layout()
    plt.show()

    # ---- pooled 输出 ----
    if pooled is not None:
        print("\n[POOLED ESTIMATE]")
        print(f"switch_col: {pooled['switch_col']}")
        print(f"datasets used: {pooled['n_datasets_used']}")
        print(f"pooled delta_raw = mean1-mean0: {pooled['pooled_delta_raw']:.6f}")
        print(f"pooled delta_consumption = -(mean1-mean0): {pooled['pooled_delta_consumption']:.6f}")


# =========================================================
# 4) 一键跑：gps_status + gps_activity
# =========================================================
def run_pgps_module(mcm_data_filtered_list, use_control=True):
    # ---- gps_status ----
    control_cols_status = CONTROL_COLS_BASE + [GPS_ACTIVITY_COL]  # activity 也作为控制变量固定住
    per_status, pooled_status = estimate_switch_delta(
        mcm_data_filtered_list,
        switch_col=GPS_STATUS_COL,
        control_cols=control_cols_status,
        use_control=use_control
    )
    print("\n=== gps_status summary (per dataset) ===")
    print(per_status)

    plot_switch_summary(per_status, pooled_status, title_prefix="GPS_STATUS")

    # ---- gps_activity ----
    control_cols_activity = CONTROL_COLS_BASE + [GPS_STATUS_COL]  # status 也作为控制变量固定住
    per_act, pooled_act = estimate_switch_delta(
        mcm_data_filtered_list,
        switch_col=GPS_ACTIVITY_COL,
        control_cols=control_cols_activity,
        use_control=use_control
    )
    print("\n=== gps_activity summary (per dataset) ===")
    print(per_act)

    plot_switch_summary(per_act, pooled_act, title_prefix="GPS_ACTIVITY")

    # ---- 最终 PGPS 参数（用 pooled）----
    # 直觉版参数：正数 = “开启带来功耗增加”
    alpha_status = None if pooled_status is None else pooled_status["pooled_delta_consumption"]
    alpha_act    = None if pooled_act is None else pooled_act["pooled_delta_consumption"]

    print("\n==============================")
    print("FINAL PGPS MODEL (recommended)")
    print("==============================")
    print("Let I{·} be the indicator function.")
    print("PGPS(t) = α_status * I{gps_status(t)=1} + α_activity * I{gps_activity(t)=1}")
    print("where α_status and α_activity are estimated by conditional mean differences.")
    print("")
    print(f"α_status   = {alpha_status}  (positive => more power when status=1)")
    print(f"α_activity = {alpha_act}     (positive => more power when activity=1)")

    return {
        "per_status": per_status, "pooled_status": pooled_status,
        "per_activity": per_act, "pooled_activity": pooled_act,
        "alpha_status": alpha_status, "alpha_activity": alpha_act
    }


# =========================================================
# 5) RUN（你直接执行这一行）
# =========================================================
pgps_res = run_pgps_module(mcm_data_filtered_list, use_control=USE_MODE_CONTROL)