# -*- coding: utf-8 -*-
"""ScreenTest

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l11Cs--nBmsik_Hm08FFZOMHKx7djGk6
"""

import pandas as pd
import numpy as np

def extract_filtered_rows(
    csv_path: str,
    out_path: str = None,
    encoding: str = "utf-8"
):
    # =========================
    # 1) 读入 CSV
    # =========================
    df = pd.read_csv(csv_path, encoding=encoding, low_memory=False)

    # =========================
    # 2) 兼容列名（有些数据可能写成 cpu—usage / cpu-usage / CPU Usage 等）
    #    这里做一个“列名标准化 + 映射”
    # =========================
    def norm(s: str) -> str:
        s = str(s).strip().lower()
        s = s.replace("—", "-").replace("–", "-")  # 处理长短横
        s = s.replace(" ", "_")
        s = s.replace("-", "_")
        return s

    col_map = {norm(c): c for c in df.columns}

    # 你需要的标准列名 -> 可能的别名（标准化后）
    need = {
        "bright_level": ["bright_level", "brightness", "screen_brightness", "brightlevel"],
        "cpu_usage": ["cpu_usage", "cpuusage", "cpu_use", "cpu_util", "cpu_utilization", "cpu"],
        "gps_status": ["gps_status", "gps", "gpsstatus"],
        "screen_status": ["screen_status", "screen", "screenstatus"],
        "battery_charging_status": ["battery_charging_status", "charging_status", "batterychargingstatus"],
        "battery_connection_status": ["battery_connection_status", "connection_status", "batteryconnectionstatus"],
        "battery_power": ["battery_power", "power", "battery_power_w", "batterypower"],
    }

    # 找到实际列名
    actual = {}
    missing = []
    for std_name, aliases in need.items():
        found = None
        for a in aliases:
            if a in col_map:
                found = col_map[a]
                break
        if found is None:
            missing.append(std_name)
        else:
            actual[std_name] = found

    if missing:
        raise KeyError(
            "CSV里缺少这些必要列（或列名不匹配）：\n"
            + "\n".join(missing)
            + "\n\n你现在CSV的列名有：\n"
            + ", ".join(df.columns[:50]) + (" ..." if len(df.columns) > 50 else "")
        )

    # =========================
    # 3) 转成数值（避免字符串导致比较失败）
    # =========================
    for k in actual:
        df[actual[k]] = pd.to_numeric(df[actual[k]], errors="coerce")

    # =========================
    # 4) 计算 255 的 20%~40% 对应的亮度区间
    # =========================
    bmin = int(np.ceil(1))  # 51
    bmax = int(np.floor(255)) # 102

    # =========================
    # 5) 过滤条件
    # =========================
    mask = (
        df[actual["bright_level"]].between(bmin, bmax, inclusive="both") &
        df[actual["cpu_usage"]].between(70, 95, inclusive="both") &
        (df[actual["gps_status"]] == 0) &
        (df[actual["screen_status"]] == 1) &
        (df[actual["battery_charging_status"]] == 3) &
        (df[actual["battery_connection_status"]] == 0)
    )

    df_f = df.loc[mask, [
        actual["bright_level"],
        actual["cpu_usage"],
        actual["gps_status"],
        actual["screen_status"],
        actual["battery_charging_status"],
        actual["battery_connection_status"],
        actual["battery_power"],
    ]].copy()

    # =========================
    # 6) 输出一些统计，方便你确认筛选是否合理
    # =========================
    print("=== Filter Summary ===")
    print(f"Brightness range: {bmin} ~ {bmax} (i.e., 20%~40% of 255)")
    print(f"Rows kept: {len(df_f)} / {len(df)}")
    if len(df_f) > 0:
        print("\nBattery_power stats:")
        print(df_f[actual["battery_power"]].describe())
    else:
        print("\n⚠️ 没筛到任何行：请检查列名、数据单位、或条件是否太严格。")

    # =========================
    # 7) 保存（可选）
    # =========================
    if out_path:
        df_f.to_csv(out_path, index=False, encoding="utf-8-sig")
        print(f"\nSaved to: {out_path}")

    return df_f



df_out = extract_filtered_rows(
   csv_path=r"/content/ab47b5f5ecded6b8_20221210_dynamic_processed.csv",
   out_path=r"/content/效果.csv"
 )

import matplotlib.pyplot as plt


def plot_bright_vs_battery_power(df_f):
    """
    x: bright_level
    y: battery_power
    每一行一个点
    """

    plt.figure(figsize=(7, 5))
    plt.scatter(
        df_f["bright_level"],
        df_f["battery_power"],
        s=20,
        alpha=0.6
    )

    plt.xlabel("bright_level")
    plt.ylabel("battery_power")
    plt.title("Battery Power vs Bright Level (each row = one point)")
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

df_f = extract_filtered_rows(
    csv_path=r"/content/效果.csv"
)

plot_bright_vs_battery_power(df_f)

import matplotlib.pyplot as plt

def plot_bright_with_mean_line(df_f):
    # 1) 计算 battery_power 的整体平均值
    mean_power = df_f["battery_power"].mean()

    # 2) 画散点
    plt.figure(figsize=(7, 5))
    plt.scatter(
        df_f["bright_level"],
        df_f["battery_power"],
        s=20,
        alpha=0.6,
        label="data points"
    )

    # 3) 画平均值水平线
    plt.axhline(
        y=mean_power,
        linestyle="--",
        linewidth=2,
        label=f"mean battery_power = {mean_power:.3f}"
    )

    plt.xlabel("bright_level")
    plt.ylabel("battery_power")
    plt.title("Battery Power vs Bright Level\n(with overall mean line)")
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

    return mean_power
def bright_level_stats(df_f):
    mean_b = df_f["bright_level"].mean()
    median_b = df_f["bright_level"].median()
    std_b = df_f["bright_level"].std()
    min_b = df_f["bright_level"].min()
    max_b = df_f["bright_level"].max()

    print("=== Bright Level Statistics ===")
    print(f"Mean   bright_level : {mean_b:.2f}")
    print(f"Median bright_level : {median_b:.2f}")
    print(f"Std    bright_level : {std_b:.2f}")
    print(f"Min    bright_level : {min_b}")
    print(f"Max    bright_level : {max_b}")

    return {
        "mean": mean_b,
        "median": median_b,
        "std": std_b,
        "min": min_b,
        "max": max_b
    }

mean_p = plot_bright_with_mean_line(df_f)
print("Mean battery_power =", mean_p)
stats = bright_level_stats(df_f)